arena:
  pos1:
    world: world
    x: -192
    y: 139
    z: 36
  pos2:
    world: world
    x: -162
    y: 79
    z: 6
LeavesConfig:
  Yes_Rico_Kaboom:
    Phase1:
      delay: 45
      randomtickspeed: 3
      pvp: false
      dispenser:
        min: 1
        max: 1
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"
    Phase2:
      delay: 45
      randomtickspeed: 3
      pvp: true
      dispenser:
        min: 1
        max: 2
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"
    Phase3:
      delay: 45
      randomtickspeed: 3
      pvp: false
      dispenser:
        min: 2
        max: 3
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"
    Phase4:
      delay: 45
      randomtickspeed: 5
      pvp: true
      dispenser:
        min: 5
        max: 7
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"
  Classico:
    Phase1:
      delay: 45
      randomtickspeed: 3
      pvp: false
      dispenser:
        min: 0
        max: 0
        command:
          - ""
        command_description: ""
    Phase2:
      delay: 45
      randomtickspeed: 5
      pvp: true
      dispenser:
        min: 0
        max: 0
        command:
          - ""
        command_description: ""
    Phase3:
      delay: 45
      randomtickspeed: 7
      pvp: false
      dispenser:
        min: 0
        max: 0
        command:
          - ""
        command_description: ""
    Phase4:
      delay: 45
      randomtickspeed: 15
      pvp: true
      dispenser:
        min: 0
        max: 0
        command:
          - ""
        command_description: ""
  SlimeInvasion:
    Phase1:
      delay: 45
      randomtickspeed: 3
      pvp: false
      dispenser:
        min: 1
        max: 1
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"
    Phase2:
      delay: 45
      randomtickspeed: 3
      pvp: true
      dispenser:
        min: 1
        max: 2
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"
    Phase3:
      delay: 45
      randomtickspeed: 3
      pvp: false
      dispenser:
        min: 2
        max: 3
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"
    Phase4:
      delay: 45
      randomtickspeed: 5
      pvp: true
      dispenser:
        min: 5
        max: 7
        command:
          - summon minecraft:creeper ~ ~-1 ~
        command_description: "Creeper"